/**
 * Anagrafica REST API
 * API REST relativo al componente di anagrafica
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TabDto {
  id: number;
  descrizione: string;

}
